---
title: "Research"
toc: false
page-layout: article
title-block-banner: false
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd
---

The majority of my research is in an area of pure mathematics called representation theory. I am usually  drawn to projects involving an interplay between combinatorial objects such as partitions or graphs and algebraic objects such as (super)groups or Lie (super)algebras. I am particularly interested in diagram categories related to Brauer algebras and Deligne's categories associated with representation theory in complex rank.

### Publications and Preprints

1. **Stuttering look and say sequences and a challenger to Conway's most complicated algebraic number from the silliest source**
<br>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/2206.11991" role="button">preprint</a>
<details>
	<summary>abstract</summary>
	We introduce stuttering look and say sequences and describe their chemical structure in the spirit of Conway's work on audioactive decay. We show the growth rate of a stuttering look and say sequence is an algebraic integer of degree 415.
</details>

1. **Jellyfish partition categories** 
<br>
*Algebras and Representation Theory*, **23**, 327-347 (2020).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://link.springer.com/article/10.1007/s10468-018-09851-7" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1612.05182" role="button">arXiv</a>
<details>
	<summary>abstract</summary>
	For each positive integer $n$, we introduce a monoidal category $\mathcal{JP}(n)$ using a generalization of partition diagrams. When the characteristic of the ground field is either 0 or at least $n$, we show $\mathcal{JP}(n)$ is monoidally equivalent to the full subcategory of $\operatorname{Rep}(A_n)$ whose objects are tensor powers of the natural $n$-dimensional permutation representation of the alternating group $A_n.$
</details>

1. **A basis theorem for the degenerate affine oriented Brauer-Clifford supercategory** 
<br>
(with J. Brundan and J. Kujawa) *Canadian Journal of Math.*, **71**, 1061-1101 (2019).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://www.cambridge.org/core/journals/canadian-journal-of-mathematics/article/basis-theorem-for-the-degenerate-affine-oriented-brauerclifford-supercategory/5A69C40B569D8AD84D835007C504309F" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1706.09999" role="button">arXiv</a>
<details>
	<summary>abstract</summary>
	We introduce the oriented Brauer-Clifford and degenerate affine oriented Brauer-Clifford supercategories. These are diagrammatically defined monoidal supercategories which provide combinatorial models for certain natural monoidal supercategories of supermodules and endosuperfunctors, respectively, for the Lie superalgebras of type Q. Our main results are basis theorems for these diagram supercategories. We also discuss connections and applications to the representation theory of the Lie superalgebra of type Q.
</details>

1. **Thick ideals in Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}(O_\delta)$** 
<br>
(with T. Heidersdorf) *Journal of Algebra*, **480**, 237-265 (2017).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://www.sciencedirect.com/science/article/pii/S0021869317301060" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1507.06728" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	We describe indecomposable objects in Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}(O_\delta)$ and explain how to decompose their tensor products. We then classify thick ideals in $\underline{\operatorname{Re}}\!\operatorname{p}(O_\delta)$. As an application we classify the indecomposable summands of tensor powers of the standard representation of the orthosymplectic supergroup up to isomorphism.
</details>

1. **A basis theorem for the affine oriented Brauer category and its cyclotomic quotients** 
<br>
(with J. Brundan, D. Nash, and A. Reynolds) *Quantum Topology*, **8**, 75-112 (2017).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://ems.press/journals/qt/issues/1360" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1404.6574" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	The affine oriented Brauer category is a monoidal category obtained from the oriented Brauer category (= the free symmetric monoidal category generated by a single object and its dual) by adjoining a polynomial generator subject to appropriate relations. In this article, we prove a basis theorem for the morphism spaces in this category, as well as for all of its cyclotomic quotients.
</details>


1. **Ideals in Deligne's tensor category $\underline{\operatorname{Re}}\!\operatorname{p}(GL_\delta)$** 
<br>
*Mathematical Research Letters*, **21**, 969-984 (2014).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://www.intlpress.com/site/pub/pages/journals/items/mrl/content/vols/0021/0005/a004/index.php" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1201.5669" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	We give a classification of ideals in $\underline{\operatorname{Re}}\!\operatorname{p}(GL_\delta)$) for arbitrary $\delta.$
</details>


1. **On Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}^{ab}(S_d)$** 
<br>
(with V. Ostrik) *Algebra & Number Theory*, **8**, 473-496 (2014).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://msp.org/ant/2014/8-2/p08.xhtml" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1304.3491" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	We prove a universal property of Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}^{ab}(S_d)$. Along the way, we classify tensor ideals in the category $\underline{\operatorname{Re}}\!\operatorname{p}(S_d).$
</details>


1. **Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}(GL_\delta)$ and representations of general linear supergroups** 
<br>
(with B. Wilson) *Representation Theory*, **16**, 568-609 (2012).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://www.ams.org/journals/ert/2012-16-16/S1088-4165-2012-00425-3/" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1108.0652" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	We classify indecomposable summands of mixed tensor powers of the natural representation for the general linear supergroup up to isomorphism. We also give a formula for the characters of these summands in terms of composite supersymmetric Schur polynomials, and give a method for decomposing their tensor products. Along the way, we describe indecomposable objects in $\underline{\operatorname{Re}}\!\operatorname{p}(GL_\delta)$ and explain how to decompose their tensor products.
</details>


1. **Modified traces on Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}(S_t)$** 
<br>
(with J. Kujawa) *Journal of Algebraic Combinatorics*, **36**, 541-560 (2012).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://link.springer.com/article/10.1007/s10801-012-0349-1" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/1103.2082" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	Deligne has defined a category which interpolates among the representations of the various symmetric groups. In this paper we show Deligne’s category admits a unique nontrivial family of modified trace functions. Such modified trace functions have already proven to be interesting in both low-dimensional topology and representation theory. We also introduce a graded variant of Deligne’s category, lift the modified trace functions to the graded setting, and use them to recover the well-known invariant of framed knots known as the writhe.
</details>


1. **On blocks of Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}(S_t)$** 
<br>
(with V. Ostrik) *Advances in Mathematics*, **226**, 1331-1377 (2011).
<br>
<a class="btn btn-outline-primary btn-sm" href="https://www.sciencedirect.com/science/article/pii/S0001870810003142" role="button">journal</a>
<a class="btn btn-outline-primary btn-sm" href="https://arxiv.org/abs/0910.5695" role="button">arXiv</a> 
<details>
	<summary>abstract</summary>
	Recently P. Deligne introduced the tensor category $\underline{\operatorname{Re}}\!\operatorname{p}(S_t)$ (for $t$ not necessarily an integer) which in a certain precise sense interpolates the categories $\operatorname{Rep}(S_d)$ of representations of the symmetric groups $S_d$. In this paper we describe the blocks of Deligne's category $\underline{\operatorname{Re}}\!\operatorname{p}(S_t).$
</details>







