---
title: "Student Projects"
toc: true
page-layout: article
title-block-banner: false
---

One of my favorite things to do at The College of Idaho is work with students on advanced undergraduate mathematics. You can check out some of the projects I have supervised below. I have several ideas for student projects that I'd be happy to explore with interested and motivated students. 

## Resources for My Students

#### Notes on Diagram Categories

I wrote some notes to introduce undergraduates to diagram categories. The notes do not assume the reader has any experience with category theory, or even abstract algebra. These notes include an introduction to categories, functors, and (strict) monoidal categories; with a motivation of studying various diagram categories. There are plenty of things I would like to add to the notes (presentations of categories, linear categories, etc.). However, I have found that the current version is more than sufficient to get students up to speed enough to work on projects related to diagram categories. 
<br>
<a class="btn btn-outline-primary btn-sm" href="notes/diagram_cats.pdf" role="button">notes</a>

#### An Introduction to Nonstandard Look and Say Sequences

These notes were written to introduce students to the theory of look and say sequences in the spirit of John Conway's paper [The Weird and Wonderful Chemistry of Audioactive Decay](https://link.springer.com/chapter/10.1007/978-1-4612-4808-8_53). The notes are not meant as a replacement for Conway’s
delightful explanation of his methods and results. Instead, they are meant to explain how Conway’s methods and results can be generalized to other (nonstandard) look and say sequences.
<br>
<a class="btn btn-outline-primary btn-sm" href="look_and_say/papers/intro_nonstandard_look_and_say/look_and_say_intro.pdf" role="button">notes</a>


#### The Python look_and_say module

I wrote a Python module that students (or anyone else) can use to explore nonstandard look and say sequences in the spirit of John Conway. 
<br>
<a class="btn btn-outline-primary btn-sm" href="https://pypi.org/project/look-and-say/" role="button">PyPI</a>
<a class="btn btn-outline-primary btn-sm" href="look_and_say/docs/look_and_say.html" role="button">documentation</a>
<a class="btn btn-outline-primary btn-sm" href="https://github.com/jonnycomes/look_and_say" role="button">GitHub Repo</a>



## My Students' Projects

#### Balanced Oriented Partition Categories and Generalized Permutation Groups

**Sara Warner** (2025)

In the Spring of 2025, Sara learned about how the partition category $\mathcal{P}$ is related to the representation theory of the symmetric group $\Sigma_d$. In particular, she studied the full tensor functor $\mathcal{P(d)}\to\operatorname{Rep(\Sigma_d)}$. For this project, Sara proved that there is an analogous full tensor functor $\mathcal{BOP(d)}\to\operatorname{Rep(\Gamma_d)}$ where $\Gamma_d$ is the group of $d\times d$ generalized permutation matrices and $\mathcal{BOP(d)}$ is a diagram category consisting of so-called *balanced oriented partition diagrams*. Sara gave a poster presentation of this result at the 2025 SRC.

<a class="btn btn-outline-primary btn-sm" href="studentwork/SRC_2025_Sara_Warner.pdf" role="button">poster</a>


#### Jellyfish Brauer Categories Related to Special Orthosymplectic Supergroups

**Ethan Bassingthwaite, Ryan Blau, Michael Coleman, and Julene Elias** (2023-24)

In the Spring of 2023, this jellyfish crew studied the diagram category $JB(2)$ which is equivalent to the full tensor subcategory of Rep(SO(2)) generated by the natural 2-dimensional representation of the special orthogonal group SO(2). The main result of the project was a diagram basis for $JB(2)$ in terms of dotted Temperley-Lieb diagrams. They wrote up their result nicely in a paper. The following year, the four students continued their work, making good progress on similar theorems for jellyfish Brauer categories related to special orthosymplectic Lie superalgebras $\mathfrak{sosp}(1|2)$ and $\mathfrak{sosp}(2|2)$. In Spring 2024, the four students gave a poster presentation of all their results at the SRC. 

<a class="btn btn-outline-primary btn-sm" href="studentwork/Paper_Bassingthwaite_Blau_Coleman_Elias.pdf" role="button">paper</a>


#### A Python Proof of Conway's Cosmological Theorem 

**Ethan Bassingthwaite and Monika de los Rios** (2022)

In the Spring of 2022, Ethan and Monika implemented a proof of John Conway's Cosmological Theorem using Python. We followed the strategy of [Zeilberger's proof](https://www.ams.org/journals/era/1997-03-11/S1079-6762-97-00026-7/S1079-6762-97-00026-7.pdf) with implementation similar to that of [Litherland](https://oeis.org/A005150/a005150_4.pdf).
This proof was subsequently added to the Python module I wrote called look_and_say.
<br>
<a class="btn btn-outline-primary btn-sm" href="https://jonnycomes.github.io/look_and_say/docs/look_and_say.html#proof-of-conways-cosmology-theorem" role="button">documentation</a>




#### $n$th Root 2 Binary Look and Say Sequences

**Santosh Acharya and Aspram Kharatyan** (2021-22)

This project was completed during the Math Capstone course in the Fall of 2021. Santosh and Aspram explored various nonstandard look and say sequences coming from nonstandard binary number systems using base $\sqrt[n]{2}$ for various positive integers $n.$ Their results include descriptions of the growth rates and chemistry of the squences for particular seeds, as well as a Cosmological Lemma which can be used to completely describe the chemistry for all seeds at any particular choice of $n$. Santosh and Aspram wrote up the details of their work in a paper and presented a poster summarizing their work at the 2022 SRC.
<br>
<a class="btn btn-outline-primary btn-sm" href="studentwork/Paper_Acharya_and_Kharatyan.pdf" role="button">paper</a>
<a class="btn btn-outline-primary btn-sm" href="studentwork/SRC_Acharya_and_Kharatyan.pdf" role="button">poster</a>

#### Higher Dimensional Twindragons via Quaternions

**Alex Tarasenko** (2019 - 2020)

This project started with a reading course in the Fall of 2019 on *Measure, Topology, and Fractal Geometry* by Edgar. A particularly beautiful topic in that book is the connection between various representations of complex numbers and fractilings of the complex plane. The following spring, Alex explored higher dimensional analogs of this topic by replacing the 2-dimensional complex numbers with the 4-dimensional quaternion algebra (the Hamiltonians). Alex presented his results at the 2020 SRC. Unfortunately, I do not have a copy of Alex's poster to share. 

#### Factor Groups of Knot and LOG Groups

**Samuel Chandler** (2015 - 2017)

This project started as a summer reading on knot theory using *The Knot Book* by Adams. The following academic year, Sam learned to code in a computer algebra system called GAP in order to study factor groups of knot groups. Sam also studied quotients of generalizations of knot groups that arise from labeled oriented graphs.
Sam presented his work at the 2016 SRC. 
<br>
<a class="btn btn-outline-primary btn-sm" href="studentwork/SRC_2016_Sam_Chandler.pdf" role="button">poster</a>

#### Applications of Galois Theory to Differential Equations

**Colton Grainger** (2016)

Colton worked through the beautiful text *Galois' Dream: Group Theory and Differential Equations* by Michio Kuga. This required Colton to apply methods from topology, algebra, and complex analysis in order to obtain a deeper understanding of the theory of differential equations.
Colton presented examples at the 2016 SRC.
<br>
<a class="btn btn-outline-primary btn-sm" href="studentwork/SRC_2016_Colton_Grainger.pdf" role="button">poster</a>


#### Generators and Relations for the Motzkin Category

**Jacob Karn** (2016)

This project was an introduction to diagram categories. Jake worked through a draft of notes that I wrote, and ultimately proved a theorem which gives a nice presentation of the Motzkin category.
Jake presented his work at the 2016 SRC. 
<br>
<a class="btn btn-outline-primary btn-sm" href="studentwork/SRC_2016_Jacob_Karn.pdf" role="button">poster</a>






